# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='site_url',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
